meta_product_name: "Vamos"
meta_title: "Vamos - Support local causes. Do it with your friends."
meta_description: "Find opportunities around you, build a team, volunteer together."
meta_image: "strongtogether.jpg" # should exist in `app/assets/images/`
